### ISSUE TITLE
Décalage

### ISSUE THREAD

**Issue by Chnapy** [PokeMMOFR/PokeMMO-FR#5]
Les traductions sont décalées, surtout pour les descriptions des capacités.
Exemple : le sort Racines possède la description de Provocation, Pouv. Antique possède la description de Danse Pluie.
Aussi, la phrase que prononce le Safari lorsque la cloche sonne est hors-sujet (un truc comme "Voici votre pokémon").

- [x] Décalage des descriptions des capacités des Pokémons.
- [x] Décalage des dialogues de Kanto.

**Comment by Fu2chN** [comment]
Les capacités" des Pokémons ont été remises comme il faut depuis la 0.2.0
Je m'occupe en ce moment des dialogues. (1081 ligne à revoir.)

Ce décalage est dû à des strings supplémentaires dans la version US.

**Comment by Fu2chN** [comment]
Beta teste de la traduction visant à remettre les bonnes IDs aux bons strings.
Merci d'utiliser une rom US non patcher.

https://github.com/Fu2chN/PokeMMO-FR/releases/tag/0.2.1b
